version: '2'

services:
  tvheadend:
    container_name: tvheadend
    image: wiserain/tvheadend:stable
    restart: always
    ports:
      - "9981:9981"
      - "9982:9982"
    volumes:
      - ./config:/config
      - ./recordings:/recordings
      - ./epg2xml:/epg2xml
    environment:
      - PUID=0
      - PGID=0
      
