version: '2'

services:
  tvheadend:
    container_name: tvheadend
    image: tvheadend
    restart: always
    network_mode: "host"
    volumes:
      - ./config:/config
      - ./recordings:/recordings
      - ./epg2xml:/epg2xml
    environment:
      - PUID=0
      - PGID=0
      
