version: '2'

services:
  tvheadend:
    build: .
    restart: always
    network_mode: "host"
    volumes:
      - ./config:/config
      - ./recordings:/recordings
      - ./epg2xml:/epg2xml
      - ./dvb:/dev/dvb
    environment:
      - PUID=0
      - PGID=0
      
