version: '2'

services:
  tvheadend:
    container_name: tvheadend
    image: wiserain/tvheadend:stable
    restart: always
    network_mode: "host"
    volumes:
      - ./config:/config
      - ./recordings:/recordings
      - ./epg2xml:/epg2xml
    devices:
      - "/dev/bus/usb/001/002:/dev/bus/usb/001/002"      
    environment:
      - PUID=0
      - PGID=0
      
